# name: Test Docker Image

# on:
#   push:
#     branches: [main]
#   pull_request:
#     branches: [main]

# jobs:
#   test:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4

#       - name: Set up Python
#         uses: actions/setup-python@v5
#         with:
#           python-version: "3.12"

#       - name: Install test dependencies
#         run: pip install -r requirements-test.txt

#       - name: Build test image
#         run: docker build -t dagster-core:latest .

#       - name: Run tests
#         run: pytest tests/
