name: Test Docker Image

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install UV
        uses: astral-sh/setup-uv@v2
        with:
          version: "latest"

      - name: Generate lock file
        run: |
          [ ! -f uv.lock ] && uv pip lock --output uv.lock || echo "Lock file already exists"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build test image
        uses: docker/build-push-action@v6
        with:
          context: .
          load: true
          tags: dagster-core:test
          build-args: |
            INSTALL_DEV=true
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Test Python and UV installation
        run: |
          docker run --rm dagster-core:test \
            python -c "import sys, dagster; print(f'Python {sys.version}\\nDagster version: {dagster.__version__}')"
          docker run --rm dagster-core:test \
            bash -c "which uv && uv --version"

      - name: Test dependency installation
        run: |
          docker run --rm dagster-core:test \
            python -c "import dagster_postgres, dagster_aws; print('Required dependencies loaded successfully')"

      - name: Create basic test
        run: |
          mkdir -p tests
          cat > tests/test_basic.py << 'EOF'
          def test_basic():
              """Basic test to verify pytest works"""
              assert True

          def test_dagster_import():
              """Test that dagster can be imported"""
              import dagster
              assert dagster.__version__
          EOF

      - name: Run simple test
        run: |
          docker run --rm \
            -v ${{ github.workspace }}/tests:/opt/dagster/app/tests:ro \
            dagster-core:test \
            bash -c "cd /opt/dagster/app && pytest tests/test_basic.py -v"
