name: Test Docker Image

on:
  push:
    branches: [main]
    paths:
      - "Dockerfile"
      - "requirements.txt"
      - "tests/**"
      - "core/dagster_home/**"
      - "docker-compose.yml"
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build test image
        run: docker build -t dagster-core:latest .

      - name: Test base image functionality
        run: |
          docker run --rm dagster-core:latest \
            python -c "import dagster; print(f'Dagster version: {dagster.__version__}')"

      - name: Install test dependencies and run tests
        run: |
          docker run --rm \
            -v $(pwd)/tests:/app/tests \
            dagster-core:latest \
            sh -c "pip install -r tests/requirements-test.txt && python -m pytest tests/"

      - name: Test Dagster configuration
        run: |
          docker run --rm \
            -v $(pwd)/core/dagster_home:/opt/dagster/dagster_home \
            dagster-core:latest \
            dagster config validate

      - name: Create test network
        run: docker network create dagster_network || true

      - name: Test docker-compose configuration
        run: docker-compose config
