name: Test Docker Image

on:
  push:
    branches: [main]
    paths:
      - "Dockerfile"
      - "requirements.txt"
      - "tests/**"
  pull_request:
    branches: [main]
    paths:
      - "Dockerfile"
      - "requirements.txt"
      - "tests/**"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build test image
        run: docker build -t dagster-core:latest .

      - name: Test base image functionality
        run: |
          docker run --rm dagster-core:latest \
            python -c "import dagster; print(f'Dagster version: {dagster.__version__}')"

      - name: Run tests
        run: |
          docker run --rm \
            -v $(pwd)/tests:/app/tests \
            dagster-core:latest \
            pytest tests/
