name: Test Docker Image

on:
  push:
    branches: [main]
    paths:
      - "Dockerfile"
      - "pyproject.toml"
      - "uv.lock"
      - "tests/**"
      - "core/dagster_home/**"
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install UV
        uses: astral-sh/setup-uv@v2
        with:
          version: "latest"

      - name: Generate lock file
        run: |
          [ ! -f uv.lock ] && uv pip lock --output uv.lock || echo "Lock file already exists"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build test image
        uses: docker/build-push-action@v6
        with:
          context: .
          load: true
          tags: dagster-core:test
          build-args: |
            INSTALL_DEV=true
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Verify Dagster installation
        run: |
          docker run --rm dagster-core:test python -c "import dagster; print(f'Dagster version: {dagster.__version__}')"

      - name: Run tests
        run: |
          docker run --rm \
            -v ${{ github.workspace }}/tests:/app/tests:ro \
            dagster-core:test \
            pytest tests/ -v

      - name: Validate Dagster config
        run: |
          docker run --rm \
            -v ${{ github.workspace }}/core/dagster_home:/opt/dagster/dagster_home:ro \
            dagster-core:test \
            dagster config validate
